version: '3.8'

services:
  microservice-clientui:
    build: ./microservice-clientui
    container_name: microservice-clientui
    depends_on:
      - microservice-gateway
    ports:
      - 9091:9091
    environment:
      LINK_TO_THE_GATEWAY: "http://microservice-gateway:8181"
    networks:
      - microservices-network

  microservice-gateway:
    build: ./microservice-gateway
    container_name: microservice-gateway
    ports:
      - 8181:8181
    environment:
      SPRING_CLOUD_GATEWAY_ROUTES[0].URI: "http://microservice-patient:8084"
      SPRING_CLOUD_GATEWAY_ROUTES[0].PREDICATES[0]: "Path=/api/patient/**"
      SPRING_CLOUD_GATEWAY_ROUTES[1].URI: "http://microservice-notes:8081"
      SPRING_CLOUD_GATEWAY_ROUTES[1].PREDICATES[0]: "Path=/api/notes/**"
      SPRING_CLOUD_GATEWAY_ROUTES[2].URI: "http://microservice-diabetes-risk:8082"
      SPRING_CLOUD_GATEWAY_ROUTES[2].PREDICATES[0]: "Path=/api/diabeterisk/**"
    networks:
      - microservices-network

  microservice-patient:
    build: ./microservice-patient
    container_name: microservice-patient
    depends_on:
      - mysql-db
    ports:
      - 8084:8084
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/patient_db"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - microservices-network

  mysql-db:
    image: mysql:8.0
    volumes:
      - mysql-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: patient_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    networks:
      - microservices-network

  microservice-notes:
    build: ./microservice-notes
    container_name: microservice-notes
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/note_db"
    networks:
      - microservices-network

  mongodb:
    image: mongo
    volumes:
      - mongodb:/data/db
    restart: always
    ports:
      - 27018:27017
    networks:
      - microservices-network

  microservice-diabetes-risk:
    build: ./microservice-diabetes-risk
    container_name: microservice-diabetes-risk
    depends_on:
      - microservice-gateway
    ports:
      - 8082:8082
    environment:
      LINK_TO_THE_GATEWAY: "http://microservice-gateway:8181"
    networks:
      - microservices-network

volumes:
  mysql-db:
  mongodb:

networks:
  microservices-network:
    external:
      name: medilabo-solution_default
